name: random_bikes_generator
description: Project that generates images using Unsplash API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  unsplash_client: ^2.1.0+3
  json_annotation: ^4.8.0


dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
